# Generated by Django 4.2.19 on 2025-02-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0038_remove_questsubmission_draft_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questsubmission',
            name='video_progress',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary with 'start'(int), 'end'(int), and 'watched'(list of [start, end] ranges) for video ptrogress)", null=True),
        ),
    ]
